### ISSUE TITLE
How do you use it with webpack?

### ISSUE THREAD

**Issue by istinspring** [alansouzati/react-router-to-array#1]
I can't figure out how to import react-router-to-array inside webpack.config.js

```
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                                                                          ^^^^^^
```

**Comment by istinspring** [comment]
got it, just need to 

```
  require("babel-register");  // to import jsx files
```

**Comment by alansouzati** [comment]
I don't think you need babel if you are using the lib. You only need babel if you are for some reason using the source version (src)

**Comment by GU5TAF** [comment]
I ran into a similar issue where I had to specify my file extensions of my imports and not rely on webpack resolving them for me else it'd error with `Cannot find module './app'`.
