### ISSUE TITLE
Usage with webpack plugin

### ISSUE THREAD

**Issue by oojacoboo** [alansouzati/react-router-to-array#3]
How are you going about using this with the webpack plugin when the JSX needs to be imported prior to the webpack loaders being fired?  I'm actually using Typescript, but also okay leaving the JSX as raw js and not importing a TS file.

Do you have any sample code of that implementation?  That'd be awesome.

**Comment by alansouzati** [comment]
Do you have any example of your configuration? In theory if you have access to the router object, being JSX or not, you can call this library from anywhere. It would help to see an example of what you are trying to achieve.

**Comment by oojacoboo** [comment]
Something like this...

*webpack.config.js*
```
const reactRouterToArray = require('react-router-to-array')
const Routes = require('route/to/file/with/JSX/Routing');
const routesArray = reactRouterToArray(Routes);

module.exports = {
  //webpack config
}
```

*Routing.tsx*
```
import * as React from 'react';
import { Route, Redirect, IndexRoute } from 'react-router';
import App from 'container/App';
import Foo from 'page/Foo';

export default const Routing = (
  <Route path='/' component={App}>
    <Route path='foo' component={Foo} />
  </Route>
);
```

**Comment by alansouzati** [comment]
I guess you are looking for the StaticSiteGeneratorPlugin config?

```
const StaticSiteGeneratorPlugin = require('static-site-generator-webpack-plugin');
const reactRouterToArray = require('react-router-to-array')
const Routes = require('route/to/file/with/JSX/Routing');
const paths = reactRouterToArray(Routes);

module.exports = {
 
  entry: {
    'main': './index.js'
  },
 
  output: {
    filename: 'index.js',
    path: 'dist',
    /* IMPORTANT!
     * You must compile to UMD or CommonJS
     * so it can be required in a Node context: */
    libraryTarget: 'umd'
  },
 
  plugins: [
    new StaticSiteGeneratorPlugin('main', paths, {
      // Properties here are merged into `locals` 
      // passed to the exported render function 
      greet: 'Hello'
    })
  ]
 
};
```

**Comment by oojacoboo** [comment]
No, not looking for the config at all.  What I'm saying is that the `paths` have to be passed into the StaticSiteGeneratorPlugin.  That's a plugin that's defined in the webpack config.  Therefore, the JSX routes have to be parsed prior to being passed in.

When requiring the `Routing` in this example, it doesn't work because the loaders haven't been initialized yet.  Therefore, JSX is not recognized because webpack doesn't support JSX, or ES6 for that matter (imports, etc.)

**Comment by alansouzati** [comment]
I see, I'm sorry it took me so long to get it.

I would say you have two options, change your routes code to use JSON syntax (this is what I prefer).

Or, rename your webpack file name to include `babel.js`, for example: `webpack.config.babel.js`.

If you choose the second option you will need to include the babel-register in your package.json:

https://www.npmjs.com/package/babel-register

**Comment by oojacoboo** [comment]
I was afraid of that - using Typescript :/

I wonder if Typescript has a compile-time require hook.  Not sure if the JSON syntax will be enough for this to work since the `Routing` includes a lot of other files that include other files, and so on.  It'd be a nice dependency soup.

**Comment by alansouzati** [comment]
Interesting point, take a look at this config here:

https://github.com/grommet/grommet-docs/blob/master/site-generator.webpack.config.js

This does not have the babel suffix, and the routes are in JSON format. it works without having to run babel.

**Comment by oojacoboo** [comment]
Cool, thanks.  I'll give this all a go.

**Comment by alansouzati** [comment]
hey @oojacoboo any updates here?

**Comment by oojacoboo** [comment]
Well, I was starting to make some progress by putting the require for the tsx within the StaticSiteGeneratorPlugin's function arg.  However, I'm running into an error I can't track down because Node's stack traces are worthless.

`self.outputRules.map is not a function`

I'm pretty sure it's that the output isn't a clean array, but not sure what's causing it exactly - still working on it.  Any thoughts?

**Comment by oojacoboo** [comment]
@alansouzati I forked the static-render-webpack-plugin to add Typescript support and internally supports the react-router-to-array module.  Thanks again for your help!

https://github.com/oojacoboo/typescript-react-router-static-html-webpack-plugin
