### ISSUE TITLE
BUG: `route/:param` fails

### ISSUE THREAD

**Issue by blainekasten** [alansouzati/react-router-to-array#4]
The following test fails:

```js
const results = toArray(
  <Route path="/root">
    <Route path="/route/:param" />
  </Route>
);

expect(results).toBe([
  '/root',
  '/root/route/:param',
]);

actual([
  '/root'
]);
```

It bails out here: https://github.com/alansouzati/react-router-to-array/blob/master/src/index.js#L36

**Comment by alansouzati** [comment]
Actually this is the expected behavior. I list this limitation in the README page.

> Dynamic routes and their corresponding nested static routes are ignored. No match (*) route is also ignored. See usage example below.

I'm sorry I should have made it more clear. But this plugin is intended to list all the static routes only.
